-- Bulk insert prompts 7–365 across 13 themes
insert into prompts (text) values
  ('When did you last feel proud of yourself for something nobody noticed?'),
  ('What is one thing you can let go of this week?'),
  ('Describe a place (real or imagined) where your mind feels quiet.'),
  ('What is one thing you feel you “should” do and haven’t?  Can you reframe it?'),
  ('What feeling do you find hardest to name?'),
  ('What is your earliest memory of feeling completely safe?'),
  ('When you are anxious, what helps even a little?'),
  ('What would it look like to be 10% kinder to yourself this week?'),
  ('What is a thought you keep returning to and is it serving you?'),
  ('What part of your day belongs only to you?'),
  ('What would you do today if no one were watching or judging?'),
  ('When did you last cry, and what did the tears tell you?'),
  ('What boundary have you wanted to set but haven''t yet?'),
  ('Name three sensations you can feel right now.'),
  ('What old story about yourself are you ready to revise?'),
  ('If your body could speak right now, what would it say?'),
  ('What is one way you''ve grown that no one in your life has remarked on?'),
  ('Who in your life lets you be your full self?'),
  ('What does a good morning look like for you and how often do you make space for it?'),
  ('What "small" wins are you brushing past today?'),
  ('What is one self-critical thought you can challenge with evidence?'),
  ('When did you last give yourself permission to do nothing?'),
  ('What is the most loving thing you''ve said to yourself this week?'),
  ('Where in your life are you running on fumes? What would refilling look like?'),
  ('Who is one person you''ve never properly thanked? What would you say?'),
  ('What is something small you saw today that made the world feel kinder?'),
  ('Which of your basic comforts do you most take for granted?'),
  ('What is a skill someone else taught you that you still use?'),
  ('What''s a sound that makes you feel at home?'),
  ('Which stranger has stayed in your memory for a kind gesture?'),
  ('What''s something your past self worked hard to build that you now live inside of?'),
  ('Name a meal that always brings up gratitude when you eat it.'),
  ('Which season of your life are you most grateful you survived?'),
  ('What''s a piece of technology you''d hate to live without and who built it?'),
  ('Whose work behind the scenes makes your day possible?'),
  ('What is one thing about your body you''re grateful for today?'),
  ('What''s a book, song, or film that arrived in your life at exactly the right time?'),
  ('Who in your community do you owe more thanks to than you''ve offered?'),
  ('What''s the most generous thing a stranger has ever done for you?'),
  ('What is something free that feels priceless to you?'),
  ('Which of your "ordinary" days, looking back, was actually a gift?'),
  ('What is a friendship that surprised you with how much it gave you?'),
  ('What is something you complained about a year ago that no longer bothers you?'),
  ('Whose laugh do you carry around in your memory?'),
  ('What do you have today that you once hoped for?'),
  ('Which of your senses brought you the most joy this week?'),
  ('What is a teacher''s lesson that still shapes how you live?'),
  ('What is a memory that, even years later, still makes you smile?'),
  ('Whose patience with you when you were learning do you still appreciate?'),
  ('What is something you almost lost but didn''t?'),
  ('Who showed up for you when they didn''t have to?'),
  ('What is one luxury hiding inside your routine that you rarely notice?'),
  ('Which of your "problems" today would your younger self envy?'),
  ('What is one piece of advice you''re glad you took?'),
  ('What is one generous or good deed you have done or will do today?'),
  ('Whose day could you make better with a single text right now?'),
  ('When was the last time you helped someone without being asked? How did it feel?'),
  ('What is a kindness you''ve been meaning to offer but haven''t yet?'),
  ('Who in your life could use a check-in this week?'),
  ('What is one thing you could do today that costs nothing but means a lot to someone?'),
  ('When did a small act of kindness change the direction of your day?'),
  ('Who could you mentor, even informally, in something you know well?'),
  ('What''s a way you could surprise someone you love this week?'),
  ('Whose name do you wish you''d asked: a barista, a neighbor, a delivery driver? What would change if you did?'),
  ('What is one cause you could give five minutes to today?'),
  ('Who taught you what generosity looks like?'),
  ('What is a kind sentence you wish you''d said in the moment and can you say it now? (E.g. To the coffee shop lady: thank you for asking me about my day.)'),
  ('What''s one way you could be a better neighbor this month?'),
  ('Who is the last person you forgave and how did it free you?'),
  ('What''s a small act of service that gives you energy rather than depletes it?'),
  ('Who could you publicly thank or credit who is usually overlooked?'),
  ('What is a skill of yours you could offer for free to someone who needs it?'),
  ('When did you last give without expecting anything back?'),
  ('What''s a quiet kindness you''ve witnessed that nobody else seemed to notice?'),
  ('Who in your life would benefit most from your full attention today?'),
  ('What is a "small" piece of litter you could pick up today that nobody asked you to?'),
  ('Whose hard work could you acknowledge by name this week?'),
  ('What''s one way you''ve made someone feel seen recently?'),
  ('What is a kindness someone showed you that you''ve never properly returned?'),
  ('Who in your life is grieving, struggling, or stretched thin and what could you do?'),
  ('What''s the most underrated act of love in your daily life?'),
  ('When was the last time you offered help and meant it, not as a performance?'),
  ('What''s a habit of kindness you''d like to build into your week?'),
  ('Who is one person whose burden you could lighten today, even slightly?'),
  ('What is your favorite memory of a strong community?'),
  ('Which community shaped you most when you were young?'),
  ('Where in your life right now do you feel a sense of belonging?'),
  ('What is a community you wish existed and could you help start it?'),
  ('Who in your neighborhood do you know by name? Who don''t you?'),
  ('What is a tradition from your family, culture, or chosen group that you want to keep alive?'),
  ('When did you last feel like "we" instead of "I"?'),
  ('What is one thing your community does better than anywhere else you''ve lived?'),
  ('Who is a quiet pillar in your community? What would happen without them?'),
  ('What''s a community space (library, park, cafe, place of worship) that has shaped your life?'),
  ('When did strangers in a crowd feel like family?'),
  ('What is one community you outgrew and what did you learn from leaving?'),
  ('Who introduced you to a community you didn''t know you needed?'),
  ('What is one barrier that keeps people in your community apart that you could help dissolve?'),
  ('Where do you feel most like yourself in a group?'),
  ('What is a community you''ve contributed to that doesn''t know your name?'),
  ('Whose story in your community deserves to be told more widely?'),
  ('What is something your community celebrates that you find meaningful?'),
  ('What is a community ritual you''d like to bring back or invent?'),
  ('When have you felt the power of many people moving together toward one thing?'),
  ('Who in your community do you disagree with but still respect? Why?'),
  ('What is one neighbor''s life that would be easier if you knew them better?'),
  ('When did a community show up for you in a moment you''ll never forget?'),
  ('What is a community you only realized you belonged to once you left it?'),
  ('Who in your life is between communities right now and could use a welcome?'),
  ('What is one online community that has enriched your offline life?'),
  ('What is your community''s greatest unmet need? What is one step toward it?'),
  ('Whose welcome made you feel like you finally belonged somewhere?'),
  ('What does "showing up" for your community actually look like for you?'),
  ('What is a strength your community has that even your community underestimates?'),
  ('What change would you make to the world if you could?'),
  ('What is one issue that quietly breaks your heart? Why that one?'),
  ('If you had a free hour every week to give to a cause, what would it be?'),
  ('What is one small action you could take today that ripples outward?'),
  ('Who first taught you that you could change something?'),
  ('What is a problem near you that nobody is solving and what would the first step look like?'),
  ('What cause feels overwhelming to you? What is the smallest version of it you could touch?'),
  ('What is something you used to think was "just the way it is" that you now know can change?'),
  ('Whose activism do you admire and what would it look like to borrow one of their habits?'),
  ('What is one thing you''ve changed your mind about recently? What shifted you?'),
  ('What change would your 80-year-old self regret not fighting for?'),
  ('What is a cause you''ve quietly supported but never publicly named?'),
  ('What is something unjust you witnessed this month? What did you do, or wish you''d done?'),
  ('Who has the least power in a room you regularly walk into? How could you amplify them?'),
  ('What is one local issue you know more about than most of your friends? Could you teach them?'),
  ('What is a global issue that has a local version on your block?'),
  ('When did you last show up physically for a cause you care about?'),
  ('What is one assumption about "people who can''t change things" that you''d like to challenge?'),
  ('What is a movement you wish you''d joined earlier?'),
  ('Who is doing the work you say you care about and how could you support them this week?'),
  ('What is one resource you have (time, money, skill, voice, a spare room) that a cause near you could use?'),
  ('What is a small win in a big fight you can celebrate today?'),
  ('What story about your community is missing from the news? Who could tell it?'),
  ('What is one thing in your daily routine that, if a thousand people did it, would change something?'),
  ('Whose lived experience do you most want to learn from before forming your next opinion?'),
  ('What is a cause that scares you to speak up about? What would it take to speak anyway?'),
  ('What is one habit of "outrage without action" you could replace with something useful?'),
  ('What is something you can build, not just protest?'),
  ('What is one form of activism you''ve dismissed and is it time to look again?'),
  ('If your community got 5% better at one thing this year, what should it be?'),
  ('What is your superpower: the thing you do effortlessly that others struggle with?'),
  ('What would your closest friend say is your hidden strength?'),
  ('What is something people thank you for that you don''t think is a big deal?'),
  ('What is a skill you''ve built that you almost never use? What would it look like to use it again?'),
  ('What is something you''re known for that you''d like to be known for less?'),
  ('What is something you''d like to be known for that you haven''t claimed yet?'),
  ('What''s one role you play in groups (peacemaker, instigator, planner, dreamer) and is it the one you want?'),
  ('When have you done something hard and surprised yourself?'),
  ('What would you teach a class on, even an unserious one?'),
  ('What is a part of your identity you''re still discovering?'),
  ('What is a label others put on you that doesn''t quite fit?'),
  ('What is a value of yours that''s non-negotiable?'),
  ('What is the title of your unwritten memoir''s first chapter?'),
  ('What is something about you that hasn''t changed since you were a child?'),
  ('What is your strongest "I''m the person who” statement?'),
  ('What was your "calling" at age 10? Does any of it still apply?'),
  ('What is a strength of yours that emerged from a struggle?'),
  ('Whose example are you quietly trying to live up to?'),
  ('What is one thing you can do that nobody in your immediate circle can?'),
  ('What is a part of your story you don''t tell often, but should?'),
  ('What is a piece of your culture or heritage you carry into rooms that don''t know about it?'),
  ('What would happen if you stopped apologizing for the loudest part of yourself?'),
  ('What''s a tiny act of self-expression that makes you feel most "you"?'),
  ('Whose voice in your head is loudest and is it yours?'),
  ('What is something you do that your family didn''t, and what does that mean to you?'),
  ('What is one thing you''ve outgrown but still pretend to enjoy?'),
  ('What is a phrase or saying you find yourself returning to?'),
  ('What is a question people ask you that you wish they''d ask differently?'),
  ('What is the most "you" thing you''ve done this month?'),
  ('If you had to choose one word for yourself this year, what would it be?'),
  ('What influence do you wish you had?'),
  ('Whose lives have you quietly shaped without their realizing it?'),
  ('What is one sentence you''d want a stranger to remember about you?'),
  ('If a younger person in your life copied one thing you do, what would you hope it is?'),
  ('What is something you want to be remembered for that isn''t on your resume?'),
  ('Whose career, life, or way of being have you nudged in a better direction?'),
  ('What is a piece of advice you keep giving that you should follow yourself?'),
  ('Whose mentor are you, even without the title?'),
  ('What is one tradition you''d like to start that could outlive you?'),
  ('What is a "best you" version of yourself that other people sometimes meet?'),
  ('What would your eulogy say if it were written today? What do you want it to say in 30 years?'),
  ('What is one thing you do for free that you''d happily do for the rest of your life?'),
  ('Who looks up to you that you haven''t noticed? How could you show up better for them?'),
  ('What is something your great-grandchild might thank you for?'),
  ('What is one specific way you''ve made someone''s life easier?'),
  ('What is something you''ve built that will outlast you?'),
  ('Whose work were you part of, even invisibly, that you''re proud to claim?'),
  ('What is one thing you wish more people would copy from you?'),
  ('What is something true you''ve said that other people repeated?'),
  ('What''s an "underground" reputation you have: something people quietly say about you?'),
  ('Whose path did you make easier by walking it first?'),
  ('What is the question you most want your kids, mentees, or successors to ask you?'),
  ('What is one lesson you''d put on a billboard if you could?'),
  ('What is something you''ve done that nobody knows about that you''re most proud of?'),
  ('If your influence doubled tomorrow, what would you point it at first?'),
  ('Who in your life knows you best and when did you last tell them so?'),
  ('Who is one person you''ve drifted from that you''d love to reconnect with?'),
  ('What is one friendship that has surprised you with its staying power?'),
  ('Who taught you what love looks like in practice?'),
  ('What is something you wish your family talked about more openly?'),
  ('What is one conversation you''ve been avoiding that would lighten everything?'),
  ('Who could you call right now, just to listen?'),
  ('What is a question you''ve never asked someone you love?'),
  ('Who in your life makes you feel like the best version of yourself?'),
  ('What does friendship mean to you at this stage of your life?'),
  ('Who has changed since you first met them in a way you admire?'),
  ('What is one apology you owe or one you''re ready to accept?'),
  ('Who is someone you used to be close to, and what would you say to them now?'),
  ('What relationship are you most proud of building from scratch?'),
  ('Who in your life is going through something quietly? How can you stand near them?'),
  ('What is one boundary that improved a relationship for you?'),
  ('Who in your family carries a story you''d like to write down before it''s lost?'),
  ('What is something you appreciate about a person you find difficult?'),
  ('Who is your "no matter what" person? Have you told them?'),
  ('What is a friendship that ended well and what made the ending good?'),
  ('Who is someone you''ve forgiven, even silently?'),
  ('What is one tradition you share with someone you love?'),
  ('Who is someone you used to envy whose path you no longer want?'),
  ('What is something you''ve learned from being loved by another person?'),
  ('Who has shown up for you in ways you didn''t realize until later?'),
  ('What is one habit that''s strengthened your most important relationship?'),
  ('Who is one person in your life you''re rooting for, hard?'),
  ('What is a memory with a loved one that gets better every time you revisit it?'),
  ('Whose presence in your life makes you braver?'),
  ('What is one way you''d like to love better this year?'),
  ('What does your life look like five years from now if everything goes well?'),
  ('What is something you''re hopeful about right now that other people aren''t?'),
  ('What is one tiny seed you''re planting today whose tree you may never sit under?'),
  ('What is a problem you believe humans will solve in your lifetime?'),
  ('What is one thing you''d love to see normalized in 10 years?'),
  ('What is a beautiful future you can almost picture but haven''t dared to say out loud?'),
  ('What is something you hope is true about the world that you can''t prove?'),
  ('What is a quiet hope you''ve carried for years?'),
  ('What would your neighborhood look like in your most hopeful version of it?'),
  ('Who is doing work that gives you hope? Have you told them?'),
  ('What is one outdated belief you''d love your kids'' generation to inherit cleansed of?'),
  ('What is one thing you no longer hope for and what replaced it?'),
  ('What kind of elder do you want to become?'),
  ('What is a vision for your own life that you''ve been too embarrassed to admit?'),
  ('What is a piece of good news you''d love to read in the paper this year?'),
  ('What is one habit you''re building now that future-you will thank you for?'),
  ('What is a tradition you''d love to pass down and to whom?'),
  ('What would the version of you who has done the inner work say to you now?'),
  ('What is one thing you believe humans are getting better at?'),
  ('What is a future memory you''d like to begin creating today?'),
  ('What is something hopeful you saw this week that no one made a fuss about?'),
  ('What is your favorite version of yourself you''ve already been? Could you visit them again?'),
  ('What is one piece of beauty in the world you don''t want to take for granted?'),
  ('What is one way the world is better than when you were born?'),
  ('What is something you trust to be true even on bad days?'),
  ('What is a "what if it works?" thought you''re avoiding?'),
  ('What is one image of a possible future that motivates you to act today?'),
  ('Who, alive today, do you most look forward to seeing thrive?'),
  ('What is one thing you want to still be doing at age 80?'),
  ('What is a hope you haven''t dared write down? Try it now.'),
  ('What is one hard thing you''ve survived that you didn''t think you would?'),
  ('What is the worst advice you ever followed and what did it teach you?'),
  ('What is one mistake you''ve made that turned into a doorway?'),
  ('What is something you can do today that the you from five years ago couldn''t?'),
  ('What is a fear you''ve outgrown?'),
  ('What is a fear that still runs you and what would it cost to stop letting it?'),
  ('What is one piece of feedback that stung but helped?'),
  ('What is something you used to think was a flaw that you now see differently?'),
  ('What is a habit that pulled you out of a dark season?'),
  ('What is a "small" failure that taught you a big lesson?'),
  ('Who saw your potential before you did?'),
  ('What is something you''ve been doing scared?'),
  ('What is one comeback story from your own life you don''t tell often?'),
  ('What is something you''re still healing from? How are you tending to it?'),
  ('What is a hard truth you finally accepted, and how did your life change?'),
  ('What is one place inside you that has gotten softer over time?'),
  ('What is one place inside you that has gotten stronger over time?'),
  ('What is a coping habit you''ve outgrown and what replaced it?'),
  ('What is the most courageous "no" you''ve said this year?'),
  ('What is something you tried that didn''t work but you''re glad you tried?'),
  ('Who taught you how to recover from setbacks?'),
  ('What is a chapter of your life you''d happily reread?'),
  ('What is one lesson you keep having to learn? Why do you think that is?'),
  ('What is something you used to chase that you no longer want?'),
  ('What is a hard conversation that made a relationship stronger?'),
  ('What is one growth you''ve made that nobody but you can see?'),
  ('What is a tool you''ve added to your emotional toolbox this year?'),
  ('Who is a version of you from years ago that you''d love to thank?'),
  ('What is one thing you''ve stopped tolerating in your life?'),
  ('What is something you''re ready to begin healing this season?'),
  ('What made you laugh this week, even quietly?'),
  ('What is one small pleasure you''d defend with your life?'),
  ('What is something you do that feels like play, even though you''re an adult?'),
  ('What is a memory of joy that arrived from nowhere?'),
  ('What food, song, or smell instantly lifts your mood?'),
  ('What is the silliest thing that has made you happy this year?'),
  ('What is something you used to love that you''ve stopped doing? Could you pick it up again?'),
  ('Whose company makes everything funnier?'),
  ('What is a hobby you''d start tomorrow if no one judged you?'),
  ('What is one place that always lifts your mood when you go there?'),
  ('What is your favorite sound in the world?'),
  ('When did you last dance, even alone?'),
  ('What is something you do "just because it''s fun"?'),
  ('What is a question you find delightful?'),
  ('What is a piece of art, music, or writing you keep returning to for joy?'),
  ('What is a memory of pure, useless, brilliant fun?'),
  ('What is something you find beautiful that other people walk past?'),
  ('When did you last surprise yourself with how much you enjoyed something?'),
  ('What is your idea of a perfect, unhurried hour?'),
  ('What is the most fun you''ve had this month? Can you do it again?'),
  ('What is something playful you''d like to bring back into your routine?'),
  ('What animal, child, or pet brought you joy recently?'),
  ('What is one thing you love about the season you''re in right now?'),
  ('What''s a tradition or ritual that feels purely joyful?'),
  ('What is your favorite kind of weather and when did you last enjoy it on purpose?'),
  ('What is the best advice you''ve ever received?'),
  ('What is something you wish someone had told you ten years ago?'),
  ('What is a lesson you keep relearning?'),
  ('What is something simple that took you a long time to understand?'),
  ('What is one piece of wisdom from an elder you carry with you?'),
  ('What is something you used to believe with certainty that you now hold loosely?'),
  ('What is one thing you''ve learned about yourself only recently?'),
  ('What is the kindest thing time has taught you?'),
  ('What is something you got wrong, and what did the correction give you?'),
  ('Who is one teacher (formal or not) you want to thank?'),
  ('What is a quote you live by and where did you find it?'),
  ('What is something you''ve learned by losing?'),
  ('What is something you''ve learned by winning?'),
  ('What is a hard-earned truth you wish you could give to a stranger?'),
  ('What is something obvious you missed for years?'),
  ('What is a "rule" you used to follow that you''ve now happily broken?'),
  ('What is something you understand now that you couldn''t have learned any other way?'),
  ('What is something a child has taught you?'),
  ('What is something you learned from a person you barely knew?'),
  ('What is a book, podcast, or conversation that shifted how you see the world?'),
  ('What is one lesson you''d put in a letter to your 18-year-old self?'),
  ('What is something you keep promising yourself you''ll learn? What would the first step be?'),
  ('What is something that has gotten clearer with age?'),
  ('What is a piece of folk wisdom from your culture that has held up?'),
  ('What is a lesson you''ve learned from work that applies to love (or vice versa)?'),
  ('What is one thing you''ve been putting off that you could begin today, however small?'),
  ('What''s a brave conversation you''d like to have this week?'),
  ('What is something you keep saying "someday" about? What''s the someday-er version of you doing?'),
  ('What is one small risk you could take this week?'),
  ('What''s a fear you''d like to test by doing something small and scary?'),
  ('What is one decision you''ve been avoiding? What does your gut say?'),
  ('What''s something you could ask for that you haven''t?'),
  ('What is one promise to yourself you''d like to keep this month?'),
  ('What''s a step toward something you care about that you could take in the next hour?'),
  ('What is one thing you''d do today if you trusted yourself fully?'),
  ('What does courage look like in your daily life: not the dramatic kind, the quiet kind?'),
  ('What is one bold thing you''ve done that you''d recommend to anyone?'),
  ('What is a "no" you need to say so a bigger "yes" has room?'),
  ('What''s one thing you could start before you feel ready?'),
  ('What is something you''ve been quietly preparing for that it might be time to begin?'),
  ('What is one act of courage you witnessed this month? Could you borrow some of it?'),
  ('What is a small habit that requires more bravery than people realize?'),
  ('What is the next right step you could take, even if you can''t see the whole staircase?'),
  ('What is one thing you''ll do this week that the future-you will be proud of?'),
  ('What is your one wish for the year ahead and what is the first step you''ll take toward it tomorrow?')
;